name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/slidebolt/*
      GONOSUMDB: github.com/slidebolt/*
      GONOSUMCHECK: github.com/slidebolt/*
    steps:
      - uses: actions/checkout@v4
      - name: Configure private repos
        run: git config --global url."https://\${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...
      - run: go build ./cmd/sb-virtual
